name: Node.js Build

on:
    push:
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
                  registry-url: https://registry.npmjs.org/
                  #cache: "npm"
                  cache-dependency-path: |
                      package-lock.json
                      packages/quick_start/package-lock.json
                      packages/azure-kusto-data/package-lock.json
                      packages/azure-kusto-ingest/package-lock.json
            - run: |
                  npm install -g npm@latest
                  npm ci
            - run: |
                  npm run checkFormat
                  npm run lint
                  npm run testPipeline
              env:
                  AUTO_TEST: true
                  LOGIN_TEST: true
                  TEST_DATABASE: "e2e"
                  APP_ID: "b699d721-4f6f-4320-bc9a-88d578dfe68f"
                  APP_KEY: ${{secrets.APP_KEY}}
                  TENANT_ID: "72f988bf-86f1-41af-91ab-2d7cd011db47"
                  ENGINE_CONNECTION_STRING: "https://sdkse2etest.eastus.kusto.windows.net"
                  DM_CONNECTION_STRING: "https://ingest-sdkse2etest.eastus.kusto.windows.net"
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v2
            - name: Publish Unit Test Results
              uses: EnricoMi/publish-unit-test-result-action@v1
              if: always()
              with:
                  files: |
                      test-results.xml
