name: Node.js Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 8
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
          cache-dependency-path: |
            azure-kusto-data/package-lock.json
            azure-kusto-ingest/package-lock.json
      - working-directory: ./azure-kusto-data
        run: |
          npm i
          npm run lint
          npm run testPipeline
      - working-directory: ./azure-kusto-ingest
        run: |
          npm i
          npm link ../azure-kusto-data
          npm run lint
          npm run testPipeline
        env:
          TEST_DATABASE : "e2e"
          APP_ID: "b699d721-4f6f-4320-bc9a-88d578dfe68f"
          APP_KEY: ${{secrets.APP_KEY}}
          TENANT_ID: "72f988bf-86f1-41af-91ab-2d7cd011db47"
          ENGINE_CONNECTION_STRING: "https://sdkse2etest.eastus.kusto.windows.net"
          DM_CONNECTION_STRING: "https://ingest-sdkse2etest.eastus.kusto.windows.net"
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: |
            azure-kusto-data/test-results.xml
            azure-kusto-ingest/test-results.xml