name: Node.js Build

on:
  push:
    branches: [ master ]
  pull_request:

permissions:
  checks: write
  pull-requests: write
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
      - run: npm ci
      - run: npm run checkFormat
        continue-on-error: true
      - run: npm run lint
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.APP_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      - run: npm run testPipeline
        env:
          AUTO_TEST: true
          LOGIN_TEST: true
          TEST_DATABASE: "e2e"
          ENGINE_CONNECTION_STRING: "https://sdkse2etest.eastus.kusto.windows.net"
          DM_CONNECTION_STRING: "https://ingest-sdkse2etest.eastus.kusto.windows.net"
          AZURE_CLIENT_ID: ${{ secrets.APP_ID }}
          AZURE_TENANT_ID: ${{ secrets.TENANT_ID }}
          # Required for running tests when using ESM, see https://kulshekhar.github.io/ts-jest/docs/guides/esm-support
          NODE_OPTIONS: "--experimental-vm-modules"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: |
            junit.xml
