name: Node.js Build

on:
  push:
    branches: [ master ]
  pull_request:

permissions:
  checks: write
  pull-requests: write
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.APP_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
      - run: npm ci
      - run: npm run checkFormat
      - run: npm run lint
      - run: npm run testPipeline
        env:
          AUTO_TEST: true
          LOGIN_TEST: true
          TEST_DATABASE: "e2e"
          APP_ID: "b699d721-4f6f-4320-bc9a-88d578dfe68f"
          TENANT_ID: "72f988bf-86f1-41af-91ab-2d7cd011db47"
          ENGINE_CONNECTION_STRING: "https://sdkse2etest.eastus.kusto.windows.net"
          DM_CONNECTION_STRING: "https://ingest-sdkse2etest.eastus.kusto.windows.net"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: |
            junit.xml
