name: Node.js Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 8
          registry-url: https://registry.npmjs.org/
        
      - name: Bump version azure-kusto-data
        working-directory: ./azure-kusto-data
        run: |
          npm version patch
      
      - name: Bump version azure-kusto-ingest
        working-directory: ./azure-kusto-ingest
        run: |
          npm version patch
      
      - name: Setup GIT and commit version bump
        run: |
          git switch -c master
          git config user.email "amshalev@microsoft.com"
          git config user.name "$GITHUB_ACTOR"
          git add *
          git commit -m 'Auto bump version'
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish new version azure-kusto-data
        working-directory: ./azure-kusto-data
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      
      - name: Publish new version azure-kusto-ingest
        working-directory: ./azure-kusto-ingest
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

