name: Node.js Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 8
          registry-url: https://registry.npmjs.org/
      
      - name: Test azure-kusto-data
        working-directory: ./azure-kusto-data
        run: |
          npm i 
          npm test
      
      - name: Test azure-kusto-ingest
        working-directory: ./azure-kusto-ingest
        run: |
          npm i
          npm test
        
      - name: Bump version azure-kusto-data
        working-directory: ./azure-kusto-data
        run: |
          npm version patch
      
      - name: Bump version azure-kusto-ingest
        working-directory: ./azure-kusto-ingest
        run: |
          npm version patch
      
      - name: Setup GIT
        run: |
          git switch -c master
          git config user.email "amshalev@microsoft.com"
          git config user.name "$GITHUB_ACTOR"
      
      - name: Push version bump
        run: |
          git add *
          git commit -m 'Auto bump version'
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish new version azure-kusto-data
        working-directory: ./azure-kusto-data
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      
      - name: Publish new version azure-kusto-ingest
        working-directory: ./azure-kusto-ingest
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

