name: Node.js Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 8
          registry-url: https://registry.npmjs.org/
      - working-directory: ./azure-kusto-data
        run: npm i
      - working-directory: ./azure-kusto-data
        run: npm test
      - working-directory: ./azure-kusto-data
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - working-directory: ./azure-kusto-ingest
        run: npm i
      - working-directory: ./azure-kusto-ingest
      - run: npm test
      - working-directory: ./azure-kusto-ingest
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
