name: Node.js Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 8
          registry-url: https://registry.npmjs.org/
      - working-directory: ./azure-kusto-data
        run: |
          npm i 
          npm test
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - working-directory: ./azure-kusto-ingest
        run: |
          npm i 
          npm test
          npm run allTest
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          TEST_DATABASE : "e2e"
          APP_ID: "b699d721-4f6f-4320-bc9a-88d578dfe68f"
          APP_KEY: ${{secrets.APP_KEY}}
          TENANT_ID: "72f988bf-86f1-41af-91ab-2d7cd011db47"
          ENGINE_CONNECTION_STRING: "https://sdkse2etest.eastus.kusto.windows.net"
          DM_CONNECTION_STRING: "https://ingest-sdkse2etest.eastus.kusto.windows.net"
