name: release
permissions:
  checks: write
  pull-requests: write
  packages: write
  deployments: write
  contents: write

on:
  push:
    tags:
      - 'v\d.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
      - name: Package
        run: |
          lerna exec -- npm pack
      - name: Github Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: packages/azure-kusto-data/*.tgz packages/azure-kusto-ingest/*.tgz packages/quick_start/*.tgz
      - name: Publish new versions
        run: |
          npm install -g npm@9.9.0
          npm ci
          npm run build
          lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
